project:
  type: website
  output-dir: docs

website:
  title: "Gabrielle Hoover"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - mp1.qmd
      - maps.qmd

format:
  html:
    theme:
      - styles.css
    css: styles.css
    toc: true



